# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dsgn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 499)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pole_zaprosa = QtWidgets.QLabel(self.centralwidget)
        self.pole_zaprosa.setGeometry(QtCore.QRect(10, 10, 631, 51))
        self.pole_zaprosa.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pole_zaprosa.setText("")
        self.pole_zaprosa.setIndent(5)
        self.pole_zaprosa.setObjectName("pole_zaprosa")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(650, 10, 141, 51))
        self.pushButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"font: 87 10pt \"Arial Black\";")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 80, 601, 51))
        self.label.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"background-color: rgb(255, 255, 255);")
        self.label.setIndent(5)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 150, 601, 51))
        self.label_2.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_2.setIndent(5)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 220, 601, 51))
        self.label_3.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_3.setIndent(5)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 290, 601, 51))
        self.label_4.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_4.setIndent(5)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 360, 601, 51))
        self.label_5.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_5.setIndent(5)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(660, 80, 131, 51))
        self.label_8.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_8.setText("")
        self.label_8.setIndent(5)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(660, 150, 131, 51))
        self.label_9.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_9.setText("")
        self.label_9.setIndent(5)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(660, 220, 131, 51))
        self.label_10.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_10.setText("")
        self.label_10.setIndent(5)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(660, 290, 131, 51))
        self.label_11.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_11.setText("")
        self.label_11.setIndent(5)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(660, 360, 131, 51))
        self.label_12.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_12.setText("")
        self.label_12.setIndent(5)
        self.label_12.setObjectName("label_12")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 430, 601, 51))
        self.label_6.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"background-color: rgb(255, 255, 255);")
        self.label_6.setText("")
        self.label_6.setIndent(5)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Поиск"))
        self.label.setText(_translate("MainWindow", "Всего матчей сыграно"))
        self.label_2.setText(_translate("MainWindow", "Всего матчей выиграно:"))
        self.label_3.setText(_translate("MainWindow", "Процент побед:"))
        self.label_4.setText(_translate("MainWindow", "Всего заложено бомб:"))
        self.label_5.setText(_translate("MainWindow", "Всего разминировано бомб:"))
